#!/bin/bash
#
# Inital Setup see:
#    https://asciidoctor.org/docs/asciidoctor-revealjs/
set -e
SRCFILE=presentation.adoc

echo "Rendering presentation.adoc"
bundle exec asciidoctor-revealjs --require asciidoctor-kroki --require asciidoctor-chart  $SRCFILE

echo "Starting Webserver on :8000"
python3 -m http.server >/dev/null 2>&1 & 

#chromium-browser http://localhost:8000/presentation.html > /dev/null &

# https://stackoverflow.com/questions/360201/how-do-i-kill-background-processes-jobs-when-my-shell-script-exits
trap 'trap - SIGTERM && kill 0' SIGINT SIGTERM EXIT

echo "Watching *.adoc for changes"
inotifywait -m -e close_write *.adoc |
while read events; do
  echo $events
  bundle exec asciidoctor-revealjs --require asciidoctor-kroki --require asciidoctor-chart $SRCFILE
done
